In [120]:
import numpy as np
import pandas as pd

In [121]:
df= pd.read_csv('Merged_Dataset.csv')

In [122]:
df.head()

Date   Latitude  Longitude      Time  Weekday  Hour  Min  \
0  2016-05-31  51.455989  -0.043536  23:01:00        1    23    1   
1  2016-05-31  51.475561  -0.075330  23:05:00        1    23    5   
2  2016-05-31  51.533030  -0.203277  23:07:00        1    23    7   
3  2016-05-31  51.553184  -0.176043  23:10:00        1    23   10   
4  2016-05-31  51.553184  -0.176043  23:10:00        1    23   10   

   Day of Month  Month    Labels  Avg Population  Avg Households  
0            31      5  No Crime       42.333333       14.000000  
1            31      5  No Crime       39.466667       15.066667  
2            31      5  No Crime      159.000000       74.000000  
3            31      5  No Crime       47.000000       17.750000  
4            31      5  No Crime       47.000000       17.750000

In [123]:
no_crime= df[df['Labels']=='No Crime']
drugs= df[df['Labels']!='Drug Possesion']
vand = df[df['Labels']!='Vandalism']
guns = df[df['Labels']!='Firearms Possesion']
skeng = df[df['Labels']!='Knife or Offensive Weapon Possesion']
fight = df[df['Labels']!='Violence']
sample_nc = no_crime.sample(10000)
sample_dg = drugs.sample(10000)
sample_vd = vand.sample(10000)
sample_sk = guns.sample(10000)
sample_ft = fight.sample(10000)
len(sample_nc)

10000

In [124]:
df['Labels'].unique()

array(['No Crime', 'Drug Possesion', 'Vandalism', 'Firearms Possesion',
       'Knife or Offensive Weapon Possesion', 'Violence'], dtype=object)

In [125]:
test2 = pd.concat([sample_nc,sample_dg,sample_vd,sample_sk,sample_ft])
df= test2


In [126]:
len(df)

50000

In [127]:
from sklearn.utils import shuffle
df = shuffle(df)

In [128]:
df = df.sample(frac=1)
tra = df[:40000]
tes = df[40000:]
df=tra

In [150]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification
#X, y = make_classification(n_samples=1000, n_features=4,n_informative=2, n_redundant=0,random_state=0, shuffle=False)
X= np.array([df['Latitude'],df['Longitude'],df['Weekday'],df['Hour'],df['Min'],df['Day of Month'],df['Month'],df['Avg Population'],df['Avg Households']])
#X= np.array([df['Latitude'],df['Longitude'],df['Weekday'],df['Hour'],df['Min'],df['Day of Month'],df['Month'],df['Avg Population']])
X= X.transpose()
y = df['Labels']
clf = RandomForestClassifier(n_estimators=100, max_depth=20,random_state=0)
Xtest= np.array([tes['Latitude'],tes['Longitude'],tes['Weekday'],tes['Hour'],tes['Min'],tes['Day of Month'],tes['Month'],tes['Avg Population'],tes['Avg Households']])
Xtest= Xtest.transpose()
clf.fit(X,y)
testpred = clf.predict(Xtest)
trainpred = clf.predict(X)

In [43]:
from sklearn.model_selection import GridSearchCV
estimators = [100]
depths = [10,15,20]
params = [{'n_estimators': estimators, 'max_depth': depths}]

forrest = RandomForestClassifier()
gridsearch = GridSearchCV(forrest, params, cv=5, scoring='f1_weighted')
gridsearch.fit(X,y)
gridsearch.best_params_

C:\Users\Dario\Anaconda3\envs\COMP6246\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Dario\Anaconda3\envs\COMP6246\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Dario\Anaconda3\envs\COMP6246\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Dario\Anaconda3\envs\COMP6246\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\U

{'max_depth': 20, 'n_estimators': 100}

In [130]:
gridsearch.best_params_
#gridsearch.cv_results_

{'max_depth': 20, 'n_estimators': 100}

In [141]:
pd.unique(testpred)

array(['No Crime', 'Drug Possesion', 'Vandalism', 'Firearms Possesion'],
      dtype=object)

In [142]:
pd.unique(tes['Labels'])

array(['No Crime', 'Drug Possesion', 'Vandalism', 'Firearms Possesion',
       'Knife or Offensive Weapon Possesion', 'Violence'], dtype=object)

In [143]:
testlabs, trainlabs = tes['Labels'], y

In [144]:
from sklearn.metrics import f1_score
from sklearn.metrics import precision_recall_fscore_support

#score, score1 = f1_score(b,a,average='micro'), f1_score(b2,a2,average='micro')
#score, score1

score, score1 = precision_recall_fscore_support(b, a, average=None, labels=pd.unique(a)), precision_recall_fscore_support(b2, a2, average=None, labels=pd.unique(a2))
score

(array([0.81019801, 0.67204301, 0.83870968, 1.        , 0.5       ]),
 array([0.99133819, 0.09137427, 0.08306709, 0.05      , 0.13333333]),
 array([0.89166149, 0.16087516, 0.15116279, 0.0952381 , 0.21052632]),
 array([7966, 1368,  626,   20,   15], dtype=int64))

In [145]:
score1

(array([0.87519625, 0.99217141, 0.99417637, 1.        , 0.93333333,
        1.        ]),
 array([0.99927666, 0.44232182, 0.45908567, 0.296875  , 0.525     ,
        0.16666667]),
 array([0.93312972, 0.61186634, 0.62812089, 0.45783133, 0.672     ,
        0.28571429]),
 array([31797,  5444,  2603,    64,    80,    12], dtype=int64))

In [146]:
clf.feature_importances_

array([0.14369762, 0.14244145, 0.06778292, 0.10172382, 0.10503822,
       0.11317693, 0.08111728, 0.12487044, 0.12015133])

In [147]:
prob= clf.predict_proba(X)

In [148]:
prob

array([[6.93215199e-02, 1.33157550e-03, 3.55947485e-04, 8.62583790e-01,
        6.62111402e-02, 1.96026723e-04],
       [8.90053232e-02, 1.02786506e-02, 9.08706666e-05, 8.52678930e-01,
        4.79462254e-02, 0.00000000e+00],
       [5.65426194e-02, 2.61678711e-03, 5.37151981e-05, 2.68297602e-01,
        6.72489276e-01, 0.00000000e+00],
       ...,
       [7.56778267e-02, 1.97447116e-04, 3.92171134e-04, 8.90455418e-01,
        3.32771372e-02, 0.00000000e+00],
       [7.47697879e-02, 2.18835452e-03, 5.62129633e-04, 8.85979899e-01,
        3.64998293e-02, 0.00000000e+00],
       [9.67083763e-02, 6.13245474e-04, 6.75310813e-04, 8.69590205e-01,
        3.22827667e-02, 1.30095794e-04]])

In [ ]:
colour_map = ['bo','ro','go','co', 'mo', 'yo']
uniq = pd.unique(b)
for i in range(len(color_map)):
    indx = b==uniq[1]
    plt.plot(Xtest[])

In [149]:
score, score1 = f1_score(testlabs,testpred,average='micro'), f1_score(trainlabs,trainpred,average='micro')
score, score1

(0.8074, 0.887725)

In [38]:
from sklearn.externals import joblib
joblib.dump(clf, "crime_random_forest_model.m")

['crime_random_forest_model.m']